/* 游戏攻略网 - 站点数据（轻量静态数据 + 可本地扩展）
 * 说明：
 * - 这里仅放“核心/示例”数据；未收录的 id 会在页面中以“建设中”兜底展示（避免 404/断链）。
 * - 请勿在此硬编码任何密钥信息。
 */

(() => {
  const data = {
    version: "20251224-1",
    site: {
      name: "游戏攻略网",
      tagline: "你的专业游戏指南",
      description:
        "游戏攻略网提供高质量的游戏攻略、技巧解析与玩家讨论，帮助你更高效地享受游戏。",
    },
    games: {
      "starlight-miracle": {
        title: "星光奇迹",
        subtitle: "东方幻想 × 现代科技的开放世界冒险",
        genre: "角色扮演 | 开放世界",
        rating: 9.4,
        year: 2023,
        updated: "2025-11-20",
        difficulty: "中等偏高",
        playtime: "45-65 小时",
        platforms: ["PC", "PS5", "Xbox Series X|S"],
        modes: ["单人", "合作"],
        tags: ["开放世界", "东方幻想", "Build", "Boss战"],
        highlights: ["探索地图与奇观", "技能流派构筑", "多阶段 Boss", "装备词条组合"],
        icon: "images/icons/starlight-miracle.svg",
        hasDeepGuide: true,
        deepGuideHref: "starlight-miracle.html",
        summary:
          "一款融合东方幻想与现代科技的开放世界角色扮演游戏。探索未知星域、打造流派构筑、挑战多阶段 Boss。",
      },
      "elden-ring": {
        title: "艾尔登法环",
        subtitle: "高自由度开放世界魂系动作RPG",
        genre: "动作角色 | 开放世界",
        rating: 9.7,
        year: 2022,
        updated: "2025-10-05",
        difficulty: "硬核",
        playtime: "70-110 小时",
        platforms: ["PC", "PS5", "PS4", "Xbox Series X|S", "Xbox One"],
        modes: ["单人", "联机合作", "PVP"],
        tags: ["魂系", "开放世界", "Boss", "Build"],
        highlights: ["路线规划与探索", "Boss 机制拆解", "流派构筑", "资源管理"],
        icon: "images/icons/elden-ring.svg",
        summary:
          "探索交界地、构筑流派、挑战高压 Boss。路线规划与资源管理是前期体验的关键。",
      },
      "baldurs-gate3": {
        title: "博德之门3",
        subtitle: "高自由度团队RPG与剧情分支",
        genre: "角色扮演 | 战术回合制",
        rating: 9.6,
        year: 2023,
        updated: "2025-12-10",
        difficulty: "高",
        playtime: "80-120 小时",
        platforms: ["PC", "PS5", "Xbox Series X|S"],
        modes: ["单人", "联机合作"],
        tags: ["回合制", "叙事", "队伍", "Build"],
        highlights: ["队伍职责搭配", "对话分支", "战术回合制", "资源循环"],
        icon: "images/icons/rpg-icon.svg",
        summary:
          "以战斗回合制与丰富对话分支为核心，队伍配置与资源管理决定整体节奏。",
      },
      "crusader-kings3": {
        title: "十字军之王3",
        subtitle: "王朝经营与策略叙事",
        genre: "策略 | 角色扮演",
        rating: 8.8,
        year: 2022,
        updated: "2025-09-08",
        difficulty: "策略向",
        playtime: "30-100 小时",
        platforms: ["PC"],
        modes: ["单人"],
        tags: ["王朝", "策略", "内政", "叙事"],
        highlights: ["婚姻联盟", "封臣管理", "继承规划", "长线扩张节奏"],
        icon: "images/icons/strategy-icon.svg",
        summary:
          "从领地治理到家族联姻，决策链条复杂但极具叙事张力，是典型的长线策略体验。",
      },
      "horizon-fw": {
        title: "地平线 西之绝境",
        subtitle: "机械兽狩猎与开放世界叙事",
        genre: "动作 | 冒险",
        rating: 9.1,
        year: 2022,
        updated: "2025-12-05",
        difficulty: "中等偏高",
        playtime: "35-55 小时",
        platforms: ["PS5", "PS4", "PC"],
        modes: ["单人"],
        tags: ["开放世界", "狩猎", "机械兽", "探索"],
        highlights: ["部位拆解", "元素克制", "装备强化", "世界探索"],
        icon: "images/icons/action-game.svg",
        summary:
          "强调弱点拆解与装备搭配的开放世界动作冒险，狩猎节奏与探索规划都很关键。",
      },
      civilization6: {
        title: "文明6",
        subtitle: "从石器时代走向未来的帝国史诗",
        genre: "策略 | 回合制",
        rating: 9.5,
        year: 2016,
        updated: "2025-08-18",
        difficulty: "策略向",
        playtime: "20-60 小时/局",
        platforms: ["PC", "Switch", "PS4", "Xbox One", "Mobile"],
        modes: ["单人", "多人"],
        tags: ["回合制策略", "科技树", "城市规划", "外交"],
        highlights: ["科技路线", "城市区位", "政策卡", "胜利条件"],
        icon: "images/icons/civilization.svg",
        summary:
          "通过城市规划、科技路线与外交博弈塑造文明。胜利条件多样，玩法深度极高。",
      },
      "devil-may-cry5": {
        title: "鬼泣5",
        subtitle: "连招、判定、风格——动作天花板",
        genre: "动作 | 砍杀",
        rating: 9.1,
        year: 2019,
        updated: "2025-07-22",
        difficulty: "中等",
        playtime: "12-20 小时",
        platforms: ["PC", "PS5", "PS4", "Xbox Series X|S", "Xbox One"],
        modes: ["单人"],
        tags: ["动作", "连招", "评分", "风格"],
        highlights: ["连段衔接", "取消机制", "评分节奏", "训练场复盘"],
        icon: "images/icons/devil-may-cry.svg",
        summary:
          "从基础连段到高阶取消，节奏与风格评分并重。练习场与关键招式理解能显著提升体验。",
      },
      sekiro: {
        title: "只狼：影逝二度",
        subtitle: "招架为王的极致刀剑对决",
        genre: "动作 | 冒险",
        rating: 9.4,
        year: 2019,
        updated: "2025-09-12",
        difficulty: "极高",
        playtime: "30-50 小时",
        platforms: ["PC", "PS4", "Xbox One"],
        modes: ["单人"],
        tags: ["魂系", "招架", "Boss", "高难"],
        highlights: ["招架节奏", "义手组合", "体势管理", "Boss 学习曲线"],
        icon: "images/icons/sekiro.svg",
        summary:
          "核心是架势条与节奏博弈。学会招架、识破与义手组合后，难度曲线会明显变友好。",
      },
      "dark-souls3": {
        title: "黑暗灵魂3",
        subtitle: "硬核动作RPG的经典标杆",
        genre: "动作角色 | 魂系",
        rating: 9.6,
        year: 2016,
        updated: "2025-09-01",
        difficulty: "高",
        playtime: "45-70 小时",
        platforms: ["PC", "PS4", "Xbox One"],
        modes: ["单人", "联机合作", "PVP"],
        tags: ["魂系", "武器质变", "Boss", "路线"],
        highlights: ["路线规划", "武器质变", "翻滚节奏", "Boss 机制"],
        icon: "images/icons/dark-souls.svg",
        summary:
          "路线选择、武器质变与体力管理是通关核心。Boss 机制理解比数值更重要。",
      },
      "god-of-war": {
        title: "战神4",
        subtitle: "北欧神话与动作叙事的融合",
        genre: "动作冒险 | 叙事",
        rating: 9.8,
        year: 2018,
        updated: "2025-08-28",
        difficulty: "中等",
        playtime: "35-55 小时",
        platforms: ["PC", "PS4"],
        modes: ["单人"],
        tags: ["动作", "叙事", "北欧", "装备"],
        highlights: ["符文技能", "装备词条", "战斗与叙事", "探索支线"],
        icon: "images/icons/god-of-war.svg",
        summary:
          "战斗与叙事紧密结合。符文技能、装备词条与属性搭配能明显改变战斗节奏。",
      },
    },
    guides: {
      "bg3-build": {
        title: "博德之门3最佳职业搭配指南",
        summary: "从职责分工与机制互补出发，构建稳定且爆发强的队伍组合。",
        icon: "images/icons/skills-guide.svg",
        tags: ["构筑", "队伍搭配", "新手友好"],
        updated: "2025-12-15",
        difficulty: "入门",
        readingTime: 8,
        steps: ["明确队伍定位", "安排职责与资源循环", "检查技能覆盖", "预留应急位", "实际战斗复盘"],
      },
      "civ6-science": {
        title: "文明6：科技胜利的终极战略",
        summary: "路线、城市规划、区域联动与关键政策卡，一次讲透科技胜利。",
        gameId: "civilization6",
        icon: "images/icons/strategy-icon.svg",
        tags: ["科技树", "城市规划", "节奏"],
        updated: "2025-11-30",
        difficulty: "进阶",
        readingTime: 10,
        steps: ["锁定关键科技线", "规划核心城市区位", "保证产能与科研点", "把握关键政策卡时机"],
      },
      "dmc5-combo": {
        title: "鬼泣5：但丁全武器连招指南",
        summary: "从基础连段到取消思路，帮助你更稳定拿到高评分。",
        gameId: "devil-may-cry5",
        icon: "images/icons/combo-guide.svg",
        tags: ["连招", "练习", "评分系统"],
        updated: "2025-10-28",
        difficulty: "高阶",
        readingTime: 12,
        steps: ["确认主武器与风格", "练习基础连段", "加入取消与派生", "控制节奏拿评分"],
      },
      "bg3-party": {
        title: "博德之门3：队伍配置与资源循环",
        summary: "围绕职责互补与控制链，保证施法位与行动点的效率。",
        gameId: "baldurs-gate3",
        icon: "images/icons/skills-guide.svg",
        tags: ["队伍配置", "资源管理", "战术"],
        updated: "2025-12-12",
        difficulty: "进阶",
        readingTime: 9,
        steps: ["确定主C与控制位", "安排前排保护与治疗", "规划法术位与消耗品", "战斗后复盘"],
      },
      "ck3-dynasty": {
        title: "十字军之王3：王朝运营与继承稳态",
        summary: "通过婚姻、继承与内政治理控制扩张节奏，避免断代与叛乱。",
        gameId: "crusader-kings3",
        icon: "images/icons/strategy-icon.svg",
        tags: ["王朝", "内政", "继承"],
        updated: "2025-09-20",
        difficulty: "进阶",
        readingTime: 11,
        steps: ["规划婚姻联盟", "稳定继承权", "管理封臣忠诚", "控制扩张节奏"],
      },
      "horizon-hunt": {
        title: "地平线：弱点拆解与狩猎效率",
        summary: "利用元素克制与部位拆解，提高对机械兽的击杀效率。",
        gameId: "horizon-fw",
        icon: "images/icons/boss-guide.svg",
        tags: ["弱点", "装备", "狩猎"],
        updated: "2025-12-05",
        difficulty: "中等",
        readingTime: 7,
        steps: ["锁定目标弱点", "准备元素弹药", "拆解关键部件", "整理掉落路线"],
      },

      "character-build": {
        title: "角色构建与属性分配",
        summary: "通用构筑方法论：目标、资源、收益与容错的平衡。",
        icon: "images/icons/skills-guide.svg",
        tags: ["通用技巧", "构筑"],
        updated: "2025-08-10",
        difficulty: "入门",
        readingTime: 6,
      },
      "rare-equipment": {
        title: "稀有装备获取指南",
        summary: "从掉落逻辑与路线规划出发，提升刷装效率并减少重复劳动。",
        icon: "images/icons/boss-guide.svg",
        tags: ["装备", "效率", "收集"],
        updated: "2025-07-18",
        difficulty: "中等",
        readingTime: 6,
      },
      "quest-guides": {
        title: "主线与支线任务攻略",
        summary: "任务优先级、关键节点与易错点汇总，避免错过奖励与剧情分支。",
        icon: "images/icons/game-icon.svg",
        tags: ["任务", "流程", "分支"],
        updated: "2025-06-30",
        difficulty: "入门",
        readingTime: 5,
      },

      "tech-tree": {
        title: "科技树路线规划：如何少走弯路",
        summary: "用“收益/回合”视角规划科技路线，把关键节点卡在正确的时间点。",
        icon: "images/icons/strategy-icon.svg",
        tags: ["策略", "节奏", "规划"],
        updated: "2025-05-18",
        difficulty: "进阶",
        readingTime: 7,
      },
      "strategy-economy": {
        title: "经济运营：资源与扩张的黄金比例",
        summary: "从资源曲线出发，建立可持续扩张的运营模型。",
        icon: "images/icons/strategy-icon.svg",
        tags: ["运营", "资源", "扩张"],
        updated: "2025-05-20",
        difficulty: "进阶",
        readingTime: 8,
      },
      "battle-tactics": {
        title: "战斗战术：以弱胜强的关键原则",
        summary: "信息、位置、节奏、交换：四个维度构成战术优势。",
        icon: "images/icons/boss-guide.svg",
        tags: ["战术", "对抗"],
        updated: "2025-04-12",
        difficulty: "中等偏高",
        readingTime: 7,
      },

      "boss-guide": {
        title: "Boss 攻略：读懂机制比堆数值更重要",
        summary: "如何拆解 Boss：招式库、惩罚窗口、资源交换与阶段转场。",
        icon: "images/icons/boss-guide.svg",
        tags: ["Boss", "机制", "容错"],
        updated: "2025-03-25",
        difficulty: "高阶",
        readingTime: 8,
        steps: ["识别阶段与招式库", "找出惩罚窗口", "规划资源交换", "记录失误点"],
      },
      "combo-guide": {
        title: "连招入门：从稳定到华丽",
        summary: "把“稳定输出”练成肌肉记忆后，再叠加取消与位移细节。",
        icon: "images/icons/combo-guide.svg",
        tags: ["连招", "练习"],
        updated: "2025-02-18",
        difficulty: "入门",
        readingTime: 5,
      },
      "skills-equipment": {
        title: "技能与装备：如何搭配出最顺手的手感",
        summary: "技能循环 + 装备词条 = 手感与强度的统一。",
        icon: "images/icons/skills-guide.svg",
        tags: ["技能", "装备", "循环"],
        updated: "2025-11-02",
        difficulty: "中等",
        readingTime: 7,
      },

      "trading-guide": {
        title: "交易系统：低风险赚取第一桶金",
        summary: "从供需与路线出发，建立稳定的交易回路与风险控制。",
        icon: "images/icons/game-icon.svg",
        tags: ["经济", "路线", "风险控制"],
        updated: "2025-01-10",
        difficulty: "中等",
        readingTime: 6,
      },
      "hidden-quests": {
        title: "隐藏任务：如何系统性地“扫图”",
        summary: "用“区域-线索-触发条件”三段式记录法，避免漏掉关键支线。",
        icon: "images/icons/game-icon.svg",
        tags: ["收集", "探索", "支线"],
        updated: "2024-12-20",
        difficulty: "入门",
        readingTime: 5,
      },
      "ship-customization": {
        title: "飞船改装：从功能到美学的统一",
        summary: "按用途配置模块：航速/载重/护盾/火力，最后再做外观美化。",
        icon: "images/icons/game-icon.svg",
        tags: ["载具", "改装", "Build"],
        updated: "2024-11-05",
        difficulty: "中等",
        readingTime: 6,
      },
    },
    topics: {
      "bg3-party": {
        title: "博德之门3最强派对组合",
        starter: "战术大师",
        summary: "你更偏好稳健四保一，还是极限爆发速推？",
        category: "RPG",
        tags: ["队伍", "Build", "战术"],
        replies: 156,
        updated: "2025-12-12",
      },
      "elden-boss": {
        title: "艾尔登法环最难 BOSS 排名",
        starter: "不死队长",
        summary: "别急着吵——先说你是哪种流派、哪个周目、有没有骨灰。",
        category: "动作",
        tags: ["Boss", "难度", "排行"],
        replies: 213,
        updated: "2025-12-08",
      },
      "upcoming-games": {
        title: "2025 年最值得期待的游戏（你投哪一票？）",
        starter: "游戏预言家",
        summary: "按类型投票 + 说出你的理由（剧情、战斗、世界观还是创新）。",
        category: "资讯",
        tags: ["年度盘点", "投票"],
        replies: 189,
        updated: "2025-12-01",
      },
      "witcher3-endings": {
        title: "巫师3最佳结局攻略",
        starter: "狼派猎魔人",
        summary: "关键在于你对希里选择的“态度”，而不只是某一个选项。",
        category: "RPG",
        tags: ["剧情", "结局"],
        replies: 98,
        updated: "2025-11-18",
      },
      "elden-ring-bosses": {
        title: "艾尔登法环 Boss 难度讨论",
        starter: "无名英雄",
        summary: "先写清楚：你的武器、等级、护符与骨灰（不然没法对齐难度）。",
        category: "动作",
        tags: ["Boss", "Build"],
        replies: 132,
        updated: "2025-11-05",
      },
      "upcoming-rpgs": {
        title: "2025 年最期待的 RPG 游戏",
        starter: "RPG爱好者",
        summary: "我先来：希望“任务设计”不要只靠跑腿凑数。",
        category: "RPG",
        tags: ["年度盘点", "期待"],
        replies: 76,
        updated: "2025-10-22",
      },
      "civ6-leaders": {
        title: "文明6领袖强度与胜利路线",
        starter: "文明学者",
        summary: "不同地图/速度/AI 难度下强度排序差异很大，先说规则再讨论。",
        category: "策略",
        tags: ["领袖", "胜利路线"],
        replies: 64,
        updated: "2025-09-30",
      },
      "ai-difficulty": {
        title: "策略游戏 AI 难度平衡",
        starter: "战术大师",
        summary: "你更接受“AI 作弊”，还是更接受“AI 很聪明但数值公平”？",
        category: "策略",
        tags: ["AI", "平衡", "难度"],
        replies: 58,
        updated: "2025-09-12",
      },
      diplomacy: {
        title: "多人策略游戏外交技巧",
        starter: "谈判专家",
        summary: "‘承诺的可验证性’与‘背刺成本’才是外交的核心。",
        category: "策略",
        tags: ["多人", "外交"],
        replies: 51,
        updated: "2025-08-28",
      },
      "dark-souls": {
        title: "魂系游戏的学习曲线：你是怎么入坑的？",
        starter: "余火守护者",
        summary: "分享你的关键转折点：从‘挫败’到‘上头’发生了什么？",
        category: "动作",
        tags: ["魂系", "学习曲线"],
        replies: 73,
        updated: "2025-08-02",
      },
      "reaction-time": {
        title: "动作游戏反应速度训练方法",
        starter: "指尖闪电",
        summary: "练习不是重复，而是‘可测量的目标 + 反馈 + 复盘’。",
        category: "动作",
        tags: ["训练", "手速"],
        replies: 45,
        updated: "2025-07-18",
      },
      controller: {
        title: "手柄 vs 键鼠：哪种更适合动作游戏？",
        starter: "设备党",
        summary: "先别站队：看游戏、看角色、看你追求的上限还是舒适。",
        category: "硬件",
        tags: ["手柄", "键鼠"],
        replies: 39,
        updated: "2025-06-26",
      },
      "starlight-leveling": {
        title: "《星光奇迹》新手求助：如何快速升级到30级？",
        starter: "星光萌新",
        summary: "分享效率最高的升级路线、日常活动与卡点避坑。",
        category: "RPG",
        tags: ["升级", "新手", "路线"],
        replies: 42,
        updated: "2025-12-18",
      },
      "aoe4-dlc": {
        title: "《帝国时代IV》新DLC值得买吗？深度分析",
        starter: "策略大师",
        summary: "从文明平衡、内容量与玩法变化角度全面拆解。",
        category: "策略",
        tags: ["DLC", "评测", "平衡"],
        replies: 87,
        updated: "2025-12-16",
      },
      "wow-guild": {
        title: "寻找《魔兽世界》公会成员",
        starter: "多人游戏爱好者",
        summary: "公会活动时间、招募职业与入会要求集中说明。",
        category: "MMO",
        tags: ["公会", "招募"],
        replies: 23,
        updated: "2025-12-15",
      },
    },
  };

  window.GKB = window.GKB || {};
  window.GKB.data = data;
})();
